---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      service: apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: apache
    spec:
      containers:
        - name: apache
          image: ghcr.io/mlibrary/dspace-containerization/dspace-apache:uid
          imagePullPolicy: Always
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: apache
  name: apache
spec:
  ports:
    - name: "apache"
      targetPort: 8888
      port: 8888
  selector:
    service: apache
