---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/mlibrary/dspace-containerization/dspace-backend:uid
          command: ["/bin/bash"]
          args: ["-c", "while (!</dev/tcp/db/5432) > /dev/null 2>&1; do sleep 1; done; /dspace/bin/dspace database migrate; catalina.sh run"]
          imagePullPolicy: Always
          env:
            - name: dspace__P__name
              value: "OpenShift Demo"
            - name: dspace__P__ui__P__url
              value: "https://frontend-dspace7-testing.apps.containersprod.art2.p1.openshiftapps.com"
            - name: dspace__P__server__P__url
              value: "https://backend-dspace7-testing.apps.containersprod.art2.p1.openshiftapps.com/server"
            - name: db__P__url
              value: "jdbc:postgresql://db:5432/dspace"
            - name: solr__P__server
              value: "http://solr:8983/solr"
          ports:
            - containerPort: 8080
            - containerPort: 8009
          volumeMounts:
            - name: dspace-assetstore
              mountPath: /dspace/assetstore
      volumes:
        - name: dspace-assetstore
          persistentVolumeClaim:
            claimName: dspace-assetstore
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  ports:
    - name: "backend"
      targetPort: 8080
      port: 8080
    - name: "backdoor"
      targetPort: 8009
      port: 8009
  selector:
    service: backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: backend
  name: dspace-assetstore
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
