---
name: Build dspace-apache image

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions

jobs:
  build:
    name: dspace-apache:${{ github.ref_name }}
    runs-on: ubuntu-latest
    # Ensure this job only executed for 'mlibrary/dspace-containerization'
    if: github.repository == 'mlibrary/dspace-containerization'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dspace-apache image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/dspace-containerization/dspace-apache:${{ github.ref_name }}'
          file: dspace/apache.dockerfile
