---
name: 1. Build dspace source image

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
    inputs:
      source_image_tag:
        description: Source Image Tag
        required: true
        default: demo
        type: choice
        options:
          - demo
      backend_github_user:
        description: Backend GitHub User
        required: true
        default: mlibrary
        type: choice
        options:
          - dspace
          - mlibrary
      backend_github_repo:
        description: Backend GitHub Repo
        required: true
        default: DSpace
        type: choice
        options:
          - DSpace
      backend_github_branch:
        description: Backend GitHub Branch
        required: true
        default: umich
        type: choice
        options:
          - dspace-7_x
          - umich
          - issue-working
      frontend_github_user:
        description: Frontend GitHub User
        required: true
        default: mlibrary
        type: choice
        options:
          - dspace
          - mlibrary
      frontend_github_repo:
        description: Frontend GitHub Repo
        required: true
        default: dspace-angular
        type: choice
        options:
          - dspace-angular
      frontend_github_branch:
        description: Frontend GitHub Branch
        required: true
        default: umich
        type: choice
        options:
          - dspace-7_x
          - umich
          - issue-working

jobs:
  build:
    name: source:${{ github.event.inputs.source_image_tag }}
    runs-on: ubuntu-latest
    # Ensure this job only executed for 'mlibrary/dspace-containerization'
    if: github.repository == 'mlibrary/dspace-containerization'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dspace-source image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/dspace-containerization/dspace-source:${{ github.event.inputs.source_image_tag }}'
          file: Dockerfile
          build-args: |
            BACKEND_GITHUB_USER=${{ github.event.inputs.backend_github_user }}
            BACKEND_GITHUB_REPO=${{ github.event.inputs.backend_github_repo }}
            BACKEND_GITHUB_BRANCH=${{ github.event.inputs.backend_github_branch }}
            FRONTEND_GITHUB_USER=${{ github.event.inputs.frontend_github_user }}
            FRONTEND_GITHUB_REPO=${{ github.event.inputs.frontend_github_repo }}
            FRONTEND_GITHUB_BRANCH=${{ github.event.inputs.frontend_github_branch }}
