---
name: Build dspace-apache:uid image

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
    inputs:
      uid:
        description: "OpenShift UID"
        required: true
        default: "1000950000"
        type: choice
        options:
          - "1000950000"

jobs:
  build:
    name: dspace-apache:uid - dspace-apache:${{ github.ref_name }} with UID ${{ github.event.inputs.uid }}
    runs-on: ubuntu-latest
    # Ensure this job only executed for 'mlibrary/dspace-containerization'
    if: github.repository == 'mlibrary/dspace-containerization'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dspace-apache:uid image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/dspace-containerization/dspace-apache:uid'
          file: dspace-uid/apache.dockerfile
          build-args: |
            REF_NAME=${{ github.ref_name }}
            UID=${{ github.event.inputs.uid }}
