---
name: 2. Build dspace-* images

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
    inputs:
      dspace_version:
        description: DSpace Version
        required: true
        default: 7.6
        type: choice
        options:
          - 7.6
          - 7_x

      source_image_tag:
        description: Source Image Tag
        required: true
        default: umich
        type: choice
        options:
          - umich
          - issue-working

jobs:
  build:
    name: dspace-*:${{ github.event.inputs.source_image_tag }}
    runs-on: ubuntu-latest
    # Ensure this job only executed for 'mlibrary/dspace-containerization'
    if: github.repository == 'mlibrary/dspace-containerization'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dspace-solr image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/dspace-containerization/dspace-solr:${{ github.sha }}, ghcr.io/mlibrary/dspace-containerization/dspace-solr:${{ github.event.inputs.source_image_tag }}'
          file: dspace/solr.dockerfile
          build-args: |
            SOURCE_IMAGE_TAG=${{ github.event.inputs.source_image_tag }}

      - name: Build and push dspace-backend image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/dspace-containerization/dspace-backend:${{ github.sha }}, ghcr.io/mlibrary/dspace-containerization/dspace-backend:${{ github.event.inputs.source_image_tag }}'
          file: dspace/backend.dockerfile
          build-args: |
            DSPACE_VERSION=${{ github.event.inputs.dspace_version }}
            SOURCE_IMAGE_TAG=${{ github.event.inputs.source_image_tag }}

      - name: Build and push dspace-frontend image
        uses: docker/build-push-action@v2
        timeout-minutes: 20
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/dspace-containerization/dspace-frontend:${{ github.sha }}, ghcr.io/mlibrary/dspace-containerization/dspace-frontend:${{ github.event.inputs.source_image_tag }}'
          file: dspace/frontend.dockerfile
          build-args: |
            SOURCE_IMAGE_TAG=${{ github.event.inputs.source_image_tag }}
